E_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
]

accounts/models.py
from django.db import models
from django.db import models


# Create your models here.


class Brand(models.Model):
    brand = models.CharField(max_length=20)

    def __str__(self):
        return self.brand


class Shop(models.Model):
    b_type = models.ForeignKey(Brand, on_delete=models.CASCADE)
    model = models.CharField(max_length=50)
    price = models.BigIntegerField()
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.model

accounts/forms.py
from .models import Shop
from django import forms


class AddUploadForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['b_type', 'model', 'price', 'image']

    def __init__(self, *args, **kwargs):
        super(AddUploadForm, self).__init__(*args, **kwargs)
        self.fields['b_type'].empty_label = "Select"

accounts/views.py
from django.shortcuts import render, redirect
from .forms import AddUploadForm
from .models import Shop, Brand
# Create your views here.


def index(request):
    mobiles = Shop.objects.all().order_by('-id')
    context = {'mobiles': mobiles}
    return render(request, 'accounts/index.html', context)


def add(request):
    if request.method == 'POST':
        form = AddUploadForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
        return redirect('add')
    else:
        form = AddUploadForm()
        print("your data is not uploaded")
    context = {'form': form}
    return render(request, 'accounts/add.html', context)

accounts/templates/accounts/add.html
{% extends 'main_template.html' %}
{% load static %}

{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
    {%csrf_token %}
   <div class="mb-3">
        <select class="form-select" aria-label="Default select example" name="b_type" id="id_b_type" required>
          <option value="" selected="">Select</option>
          <option value="1">Apple</option>
          <option value="2">Xiaomi</option>
          <option value="3">Samsung</option>
          <option value="4">Huawei</option>
          <option value="5">Nokia</option>
          <option value="7">Vivo</option>
          <option value="8">RealMe</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="model" class="form-label">Model: </label>
        <input type="text" class="form-control"  name="model" id="model" placeholder="Enter model name...."{{form.model}}
    </div>
    <div class="mb-3">
        <label for="price" class="form-label">Price: </label>
        <input type="text" class="form-control" name="price" id="price" placeholder="Enter Price...."{{form.price}}
    </div>

    <label for="image" class="form-label">Image: </label>
    <div class="form-file">
      <input type="file" class="form-file-input" id="id_image" name="image" accept="image/*" required>
      <label class="form-file-label" for="customFile">
        <span class="form-file-text">Choose file...</span>
        <span class="form-file-button">Browse</span>
      </label>
    </div>
    <div class="btn-design">
        <button type="submit" class="btn btn-success">Submit</button>
    </div>
</form>


{% endblock %}

accounts/templates/accounts/index.html
{% extends 'main_template.html' %}
{% load static %}

{% block content %}
	{% for mobile in mobiles %}
	<div class="col-4 my-2 mx-auto">
		<figure>
			<img src="{{ mobile.image.url }}" alt="gallery" class="img-fluid">
		</figure>
		<div class="font-style">
			<p>{{ mobile.model }}</p>
			<p><strong>{{ mobile.price }} tk</strong></p>
		</div>
	</div>
	{% endfor %}

{% endblock %}

accounts/templates/main_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Mobile E-Shop</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="#">Mobile E-Shop</a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
	        <li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="news.html">News</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
	            Brand
	          </a>
	          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
	            <li><a class="dropdown-item" href="#">Action</a></li>
	            <li><a class="dropdown-item" href="#">Another action</a></li>
	            <li><hr class="dropdown-divider"></li>
	            <li><a class="dropdown-item" href="#">Something else here</a></li>
	          </ul>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'add' %}">Add</a>
	        </li>
	        <!-- <li class="nav-item">
	          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
	        </li> -->
	      </ul>
	      <form class="d-flex">
	        <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
	        <button class="btn btn-outline-success" type="submit">Search</button>
	      </form>
	    </div>
	  </div>
	</nav>

	<section class="main_heading pt-2">
		<div class="container">
			<div class="row my-5">
				{% block content %}

        		{% endblock %}
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/iphone11.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>iPhone 11</p>-->
<!--						<p><strong>93999 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/iphone_11_pro.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Apple iPhone 11 Pro Max 4GB/64GB</p>-->
<!--						<p><strong>139999 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/iphone_x.png' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>iPhone X 64GB</p>-->
<!--						<p><strong>84499 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/Xiaomi_Redmi_Note_9.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Xiaomi Redmi Note 9</p>-->
<!--						<p><strong>19999 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/vivo_y50.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Vivo Y50</p>-->
<!--						<p><strong>22990  tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/vivo_v19.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Vivo V19</p>-->
<!--						<p><strong>35990 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/realme6.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Realme 6 8GB/128GB</p>-->
<!--						<p><strong>22990 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/realme2pro.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Realme 2 Pro</p>-->
<!--						<p><strong>29990 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/huaweip30pro.png' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Huawei P30 Pro</p>-->
<!--						<p><strong>89999 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/samsunggalaxyA51.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Samsung Galaxy A51</p>-->
<!--						<p><strong>29999 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
<!--				<div class="col-4 my-2 mx-auto">-->
<!--					<figure>-->
<!--						<img src="{% static '/images/OPPOreno3pro.jpg' %}" alt="gallery" class="img-fluid">-->
<!--					</figure>-->
<!--					<div class="font-style">-->
<!--						<p>Oppo Reno 3 Pro</p>-->
<!--						<p><strong>39990 tk</strong></p>-->
<!--					</div>-->
<!--				</div>-->
			</div>
		</div>
	</section>
	<footer class="footer">
		<div class="container text-center">
			<p><strong>All right reserved by &copy; Mobile E-Shop</strong></p>
		</div>
	</footer>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</body>
</html>